### ISSUE TITLE
Does not seem to be working

### ISSUE THREAD

**Issue by interbiznw** [CypherpunkSamurai/oracle-signup-bypass#1]
after a quick look, they might have changed some element names, I have it enabled and still getting forwarded to login, and copy and paste the link does not have the otn replaced with otn-pub

**Comment by CypherpunkSamurai** [comment]
Thanks for reporting the Issue :)

Also, Could you please provide me the download page URL?

**Comment by interbiznw** [comment]
No problem!


https://www.oracle.com/webapps/redirect/signon?nexturl=https://download.oracle.com/otn/java/jdk/11.0.12%2B8/f411702ca7704a54a79ead0c2e0942a3/jdk-11.0.12_linux-x64_bin.deb

is what I am getting from the browser, even with the plugin on/installed with tampermonkey(and verified its recognizing its supposed to be activated and working on that page, just does not seem to do what its intended to do)
